// backUpData
export const backUpData = [
  {
    "id": 716426,
    "image": "https://img.spoonacular.com/recipes/716426-312x231.jpg",
    "imageType": "jpg",
    "title": "Cauliflower, Brown Rice, and Vegetable Fried Rice",
    "readyInMinutes": 30,
    "servings": 8,
    "sourceUrl": "https://fullbellysisters.blogspot.com/2012/01/cauliflower-fried-rice-more-veggies.html",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": true,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 7,
    "gaps": "no",
    "preparationMinutes": 15,
    "cookingMinutes": 15,
    "aggregateLikes": 3689,
    "healthScore": 51,
    "creditsText": "Full Belly Sisters",
    "license": "CC BY-SA 3.0",
    "sourceName": "Full Belly Sisters",
    "pricePerServing": 119.36,
    "summary": "The recipe Cauliflower, Brown Rice, and Vegetable Fried Rice is ready \u003Cb\u003Ein around 30 minutes\u003C/b\u003E and is definitely a great \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E option for lovers of Chinese food. This recipe makes 8 servings with \u003Cb\u003E248 calories\u003C/b\u003E, \u003Cb\u003E7g of protein\u003C/b\u003E, and \u003Cb\u003E13g of fat\u003C/b\u003E each. For \u003Cb\u003E$1.19 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 19%\u003C/b\u003E of your daily requirements of vitamins and minerals. It works well as a hor d'oeuvre. 3689 people have made this recipe and would make it again. It is brought to you by fullbellysisters.blogspot.com. Head to the store and pick up broccoli, t grapeseed oil, sesame seeds, and a few other things to make it today. With a spoonacular \u003Cb\u003Escore of 100%\u003C/b\u003E, this dish is amazing. \u003Ca href=\"https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1230097\"\u003ECauliflower, Brown Rice, and Vegetable Fried Rice\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1238897\"\u003ECauliflower, Brown Rice, and Vegetable Fried Rice\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1403527\"\u003ECauliflower, Brown Rice, and Vegetable Fried Rice\u003C/a\u003E are very similar to this recipe.",
    "cuisines": [
      "Chinese",
      "Asian"
    ],
    "dishTypes": [
      "side dish",
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 98.7173233032227,
    "spoonacularSourceUrl": "https://spoonacular.com/cauliflower-brown-rice-and-vegetable-fried-rice-716426"
  },
  {
    "id": 715769,
    "image": "https://img.spoonacular.com/recipes/715769-312x231.jpg",
    "imageType": "jpg",
    "title": "Broccolini Quinoa Pilaf",
    "readyInMinutes": 30,
    "servings": 2,
    "sourceUrl": "https://pickfreshfoods.com/broccolini-quinoa-pilaf/",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 17,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 94,
    "healthScore": 74,
    "creditsText": "pickfreshfoods.com",
    "license": null,
    "sourceName": "pickfreshfoods.com",
    "pricePerServing": 414.24,
    "summary": "Broccolini Quinoa Pilaf requires approximately \u003Cb\u003E30 minutes\u003C/b\u003E from start to finish. For \u003Cb\u003E$4.14 per serving\u003C/b\u003E, you get a main course that serves 2. One portion of this dish contains around \u003Cb\u003E20g of protein\u003C/b\u003E, \u003Cb\u003E31g of fat\u003C/b\u003E, and a total of \u003Cb\u003E625 calories\u003C/b\u003E. Head to the store and pick up vegetable broth, onion, olive oil, and a few other things to make it today. A few people made this recipe, and 94 would say it hit the spot. It is a \u003Cb\u003Erather expensive\u003C/b\u003E recipe for fans of Mediterranean food. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. It is brought to you by Pick Fresh Foods. With a spoonacular \u003Cb\u003Escore of 98%\u003C/b\u003E, this dish is excellent. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/spring-broccolini-kale-quinoa-bowls-734866\"\u003ESpring Broccolini & Kale Quinoa Bowls\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/orange-sesame-salmon-with-quinoa-broccolini-839832\"\u003EOrange-Sesame Salmon with Quinoa & Broccolini\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/black-pepper-goat-cheese-and-chard-quinoa-with-roasted-broccolini-625829\"\u003EBlack Pepper Goat Cheese and Chard Quinoa with Roasted Broccolini\u003C/a\u003E.",
    "cuisines": [
      "Mediterranean",
      "Italian",
      "European"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 98.0942230224609,
    "spoonacularSourceUrl": "https://spoonacular.com/broccolini-quinoa-pilaf-715769"
  },
  {
    "id": 642129,
    "image": "https://img.spoonacular.com/recipes/642129-312x231.jpg",
    "imageType": "jpg",
    "title": "Easy To Make Spring Rolls",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/B5HHJWNP/easy-to-make-spring-rolls",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 3,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 22,
    "healthScore": 100,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 377.64,
    "summary": "If you want to add more \u003Cb\u003Egluten free, dairy free, and pescatarian\u003C/b\u003E recipes to your collection, Easy To Make Spring Rolls might be a recipe you should try. For \u003Cb\u003E$3.78 per serving\u003C/b\u003E, you get a hor d'oeuvre that serves 4. One serving contains \u003Cb\u003E162 calories\u003C/b\u003E, \u003Cb\u003E13g of protein\u003C/b\u003E, and \u003Cb\u003E2g of fat\u003C/b\u003E. 22 people found this recipe to be flavorful and satisfying. From preparation to the plate, this recipe takes about \u003Cb\u003E45 minutes\u003C/b\u003E. It can be enjoyed any time, but it is especially good for \u003Cb\u003ESpring\u003C/b\u003E. This recipe from Foodista requires mint leaves, garlic, chili pepper, and rice vinegar. This recipe is typical of Vietnamese cuisine. Overall, this recipe earns a \u003Cb\u003Etremendous spoonacular score of 88%\u003C/b\u003E. \u003Ca href=\"https://spoonacular.com/recipes/easy-to-make-spring-rolls-1262689\"\u003EEasy To Make Spring Rolls\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/easy-to-make-spring-rolls-1218889\"\u003EEasy To Make Spring Rolls\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/easy-to-make-spring-rolls-1531113\"\u003EEasy To Make Spring Rolls\u003C/a\u003E are very similar to this recipe.",
    "cuisines": [
      "Vietnamese",
      "Asian"
    ],
    "dishTypes": [
      "fingerfood",
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "pescatarian"
    ],
    "occasions": [
      "spring",
      "easter"
    ],
    "spoonacularScore": 98.0378952026367,
    "spoonacularSourceUrl": "https://spoonacular.com/easy-to-make-spring-rolls-642129"
  },
  {
    "id": 640062,
    "image": "https://img.spoonacular.com/recipes/640062-312x231.jpg",
    "imageType": "jpg",
    "title": "Corn Avocado Salsa",
    "readyInMinutes": 25,
    "servings": 2,
    "sourceUrl": "https://www.foodista.com/recipe/BDRS2JZG/corn-avocado-salsa",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 7,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 44,
    "healthScore": 71,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 130.73,
    "summary": "Corn Avocado Salsa might be just the hor d'oeuvre you are searching for. For \u003Cb\u003E$1.31 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 15%\u003C/b\u003E of your daily requirements of vitamins and minerals. One portion of this dish contains roughly \u003Cb\u003E5g of protein\u003C/b\u003E, \u003Cb\u003E16g of fat\u003C/b\u003E, and a total of \u003Cb\u003E237 calories\u003C/b\u003E. This recipe serves 2. 44 people have made this recipe and would make it again. This recipe from Foodista requires avocado, balsamic vinegar, cumin, and garlic. A few people really liked this Mexican dish. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. From preparation to the plate, this recipe takes around \u003Cb\u003E25 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 97%\u003C/b\u003E, this dish is spectacular. If you like this recipe, take a look at these similar recipes: \u003Ca href=\"https://spoonacular.com/recipes/avocado-corn-salsa-1329607\"\u003EAvocado Corn Salsa\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/avocado-corn-salsa-173978\"\u003EAvocado-Corn Salsa\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/avocado-corn-salsa-1305913\"\u003EAvocado-Corn Salsa\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "antipasti",
      "condiment",
      "starter",
      "snack",
      "appetizer",
      "dip",
      "antipasto",
      "hor d'oeuvre",
      "spread"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 97.7538604736328,
    "spoonacularSourceUrl": "https://spoonacular.com/corn-avocado-salsa-640062"
  },
  {
    "id": 715421,
    "image": "https://img.spoonacular.com/recipes/715421-312x231.jpg",
    "imageType": "jpg",
    "title": "Cheesy Chicken Enchilada Quinoa Casserole",
    "readyInMinutes": 30,
    "servings": 4,
    "sourceUrl": "https://www.pinkwhen.com/cheesy-chicken-enchilada-quinoa-casserole/",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": false,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": true,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 17,
    "gaps": "no",
    "preparationMinutes": 15,
    "cookingMinutes": 15,
    "aggregateLikes": 9912,
    "healthScore": 38,
    "creditsText": "pinkwhen.com",
    "license": null,
    "sourceName": "pinkwhen.com",
    "pricePerServing": 262.25,
    "summary": "Cheesy Chicken Enchilada Quinoa Casserole might be just the \u003Cb\u003EMexican\u003C/b\u003E recipe you are searching for. One serving contains \u003Cb\u003E594 calories\u003C/b\u003E, \u003Cb\u003E34g of protein\u003C/b\u003E, and \u003Cb\u003E24g of fat\u003C/b\u003E. This gluten free recipe serves 4 and costs \u003Cb\u003E$2.62 per serving\u003C/b\u003E. A mixture of corn, pepper, canned tomatoes, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes approximately \u003Cb\u003E30 minutes\u003C/b\u003E. It will be a hit at your \u003Cb\u003EAutumn\u003C/b\u003E event. Plenty of people made this recipe, and 9912 would say it hit the spot. It works well as an affordable main course. It is brought to you by Pink When. With a spoonacular \u003Cb\u003Escore of 97%\u003C/b\u003E, this dish is amazing. If you like this recipe, you might also like recipes such as \u003Ca href=\"https://spoonacular.com/recipes/cheesy-chicken-enchilada-quinoa-casserole-1317125\"\u003ECheesy Chicken Enchilada Quinoa Casserole\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/cheesy-chicken-enchilada-quinoa-casserole-1340231\"\u003ECheesy Chicken Enchilada Quinoa Casserole\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/cheesy-chicken-enchilada-quinoa-casserole-1280325\"\u003ECheesy Chicken Enchilada Quinoa Casserole\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free"
    ],
    "occasions": [
      "fall",
      "winter"
    ],
    "spoonacularScore": 97.6984481811523,
    "spoonacularSourceUrl": "https://spoonacular.com/cheesy-chicken-enchilada-quinoa-casserole-715421"
  },
  {
    "id": 798400,
    "image": "https://img.spoonacular.com/recipes/798400-312x231.jpg",
    "imageType": "jpg",
    "title": "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    "readyInMinutes": 45,
    "servings": 6,
    "sourceUrl": "https://www.foodandspice.com/2016/08/spicy-black-eyed-pea-curry-with-swiss.html",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 2,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 32,
    "healthScore": 71,
    "creditsText": "foodandspice.com",
    "license": null,
    "sourceName": "foodandspice.com",
    "pricePerServing": 94.05,
    "summary": "The recipe Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant could satisfy your Indian craving in around \u003Cb\u003E45 minutes\u003C/b\u003E. This recipe serves 6 and costs 94 cents per serving. This hor d'oeuvre has \u003Cb\u003E129 calories\u003C/b\u003E, \u003Cb\u003E7g of protein\u003C/b\u003E, and \u003Cb\u003E2g of fat\u003C/b\u003E per serving. It is brought to you by foodandspice.blogspot.com. If you have black-eyed peas, olive oil, globe, and a few other ingredients on hand, you can make it. This recipe is liked by 32 foodies and cooks. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 98%\u003C/b\u003E. This score is outstanding. Try \u003Ca href=\"https://spoonacular.com/recipes/roasted-eggplant-and-swiss-chard-lasagna-1070265\"\u003ERoasted Eggplant and Swiss Chard Lasagna\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/pumpkin-black-eyed-pea-and-coconut-curry-1065869\"\u003EPumpkin, Black-Eyed Pea, and Coconut Curry\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/spicy-black-eyed-pea-relish-31042\"\u003ESpicy Black-eyed Pea Relish\u003C/a\u003E for similar recipes.",
    "cuisines": [
      "Indian",
      "Asian"
    ],
    "dishTypes": [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 97.5859146118164,
    "spoonacularSourceUrl": "https://spoonacular.com/spicy-black-eyed-pea-curry-with-swiss-chard-and-roasted-eggplant-798400"
  },
  {
    "id": 716311,
    "image": "https://img.spoonacular.com/recipes/716311-312x231.jpg",
    "imageType": "jpg",
    "title": "Mango Fried Rice",
    "readyInMinutes": 45,
    "servings": 2,
    "sourceUrl": "https://www.afrolems.com/2015/05/02/mango-fried-rice/",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 12,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 262,
    "healthScore": 45,
    "creditsText": "afrolems.com",
    "license": null,
    "sourceName": "afrolems.com",
    "pricePerServing": 151.08,
    "summary": "Mango Fried Rice is a Chinese main course. This recipe makes 2 servings with \u003Cb\u003E486 calories\u003C/b\u003E, \u003Cb\u003E16g of protein\u003C/b\u003E, and \u003Cb\u003E4g of fat\u003C/b\u003E each. For \u003Cb\u003E$1.51 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 19%\u003C/b\u003E of your daily requirements of vitamins and minerals. Several people made this recipe, and 262 would say it hit the spot. Head to the store and pick up scotch bonnet pepper, seasoning cubes, rice, and a few other things to make it today. From preparation to the plate, this recipe takes roughly \u003Cb\u003E45 minutes\u003C/b\u003E. It is brought to you by Afrolems. It is a good option if you're following a \u003Cb\u003Egluten free and dairy free\u003C/b\u003E diet. Overall, this recipe earns a \u003Cb\u003Egreat spoonacular score of 94%\u003C/b\u003E. \u003Ca href=\"https://spoonacular.com/recipes/mango-pork-fried-rice-176007\"\u003EMango-Pork Fried Rice\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/thai-beef-mango-fried-rice-1326163\"\u003EThai Beef & Mango Fried Rice\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/thai-chicken-and-mango-fried-rice-509300\"\u003EThai Chicken and Mango Fried Rice\u003C/a\u003E are very similar to this recipe.",
    "cuisines": [
      "Chinese",
      "Asian"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [],
    "spoonacularScore": 96.9690170288086,
    "spoonacularSourceUrl": "https://spoonacular.com/mango-fried-rice-716311"
  },
  {
    "id": 715543,
    "image": "https://img.spoonacular.com/recipes/715543-312x231.jpg",
    "imageType": "jpg",
    "title": "Homemade Guacamole",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.pinkwhen.com/homemade-guacamole-recipe/",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": true,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 5,
    "gaps": "GAPS_FULL",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1330,
    "healthScore": 34,
    "creditsText": "Jen West",
    "license": null,
    "sourceName": "Pink When",
    "pricePerServing": 91.76,
    "summary": "If you want to add more \u003Cb\u003Egluten free, dairy free, paleolithic, and lacto ovo vegetarian\u003C/b\u003E recipes to your recipe box, Homemade Guacamole might be a recipe you should try. For \u003Cb\u003E92 cents per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 9%\u003C/b\u003E of your daily requirements of vitamins and minerals. This recipe makes 4 servings with \u003Cb\u003E170 calories\u003C/b\u003E, \u003Cb\u003E2g of protein\u003C/b\u003E, and \u003Cb\u003E15g of fat\u003C/b\u003E each. It is an \u003Cb\u003Einexpensive\u003C/b\u003E recipe for fans of Mexican food. Many people really liked this hor d'oeuvre. This recipe from Pink When has 1330 fans. A mixture of roma tomato, onion, pepper, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly \u003Cb\u003E45 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 97%\u003C/b\u003E, this dish is amazing. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/homemade-guacamole-883310\"\u003EHomemade Guacamole\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/homemade-guacamole-1059336\"\u003EHomemade Guacamole\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/homemade-guacamole-1170259\"\u003EHomemade Guacamole\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "antipasti",
      "condiment",
      "starter",
      "snack",
      "appetizer",
      "dip",
      "antipasto",
      "hor d'oeuvre",
      "spread"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 96.8805389404297,
    "spoonacularSourceUrl": "https://spoonacular.com/homemade-guacamole-715543"
  },
  {
    "id": 716408,
    "image": "https://img.spoonacular.com/recipes/716408-312x231.jpg",
    "imageType": "jpg",
    "title": "Greek-Style Baked Fish: Fresh, Simple, and Delicious",
    "readyInMinutes": 30,
    "servings": 4,
    "sourceUrl": "https://fullbellysisters.blogspot.com/2012/04/greek-style-baked-fish-fresh-simple-and.html",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": false,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": true,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 8,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 396,
    "healthScore": 42,
    "creditsText": "Full Belly Sisters",
    "license": "CC BY-SA 3.0",
    "sourceName": "Full Belly Sisters",
    "pricePerServing": 303.59,
    "summary": "Greek-Style Baked Fish: Fresh, Simple, and Delicious might be just the \u003Cb\u003EMediterranean\u003C/b\u003E recipe you are searching for. For \u003Cb\u003E$3.04 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 21%\u003C/b\u003E of your daily requirements of vitamins and minerals. One portion of this dish contains roughly \u003Cb\u003E28g of protein\u003C/b\u003E, \u003Cb\u003E12g of fat\u003C/b\u003E, and a total of \u003Cb\u003E343 calories\u003C/b\u003E. This recipe serves 4. Plenty of people made this recipe, and 396 would say it hit the spot. It works well as a main course. Head to the store and pick up pepper, white wine, basil, and a few other things to make it today. From preparation to the plate, this recipe takes roughly \u003Cb\u003E30 minutes\u003C/b\u003E. It is a good option if you're following a \u003Cb\u003Egluten free and pescatarian\u003C/b\u003E diet. It is brought to you by fullbellysisters.blogspot.com. Overall, this recipe earns a \u003Cb\u003Etremendous spoonacular score of 98%\u003C/b\u003E. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/simple-greek-style-baked-fish-557560\"\u003ESimple Greek Style Baked Fish\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/greek-style-baked-fish-526858\"\u003EGreek Style Baked Fish\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/delicious-greek-pastitsio-casserole-style-569500\"\u003EDelicious Greek Pastitsio {Casserole-Style}\u003C/a\u003E.",
    "cuisines": [
      "Mediterranean",
      "European",
      "Greek"
    ],
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "pescatarian"
    ],
    "occasions": [],
    "spoonacularScore": 96.6684417724609,
    "spoonacularSourceUrl": "https://spoonacular.com/greek-style-baked-fish-fresh-simple-and-delicious-716408"
  },
  {
    "id": 646043,
    "image": "https://img.spoonacular.com/recipes/646043-312x231.jpg",
    "imageType": "jpg",
    "title": "Gujarati Dry Mung Bean Curry",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/G6ZJW56S/gujarati-dry-mung-bean-curry",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 11,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 3,
    "healthScore": 100,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 164.1,
    "summary": "Gujarati Dry Mung Bean Curry takes about \u003Cb\u003E45 minutes\u003C/b\u003E from beginning to end. This main course has \u003Cb\u003E376 calories\u003C/b\u003E, \u003Cb\u003E20g of protein\u003C/b\u003E, and \u003Cb\u003E5g of fat\u003C/b\u003E per serving. This recipe serves 4 and costs $1.64 per serving. A mixture of baking powder, cumin seeds, garlic, and a handful of other ingredients are all it takes to make this recipe so flavorful. This recipe from Foodista has 3 fans. This recipe is typical of Indian cuisine. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 95%\u003C/b\u003E, which is outstanding. \u003Ca href=\"https://spoonacular.com/recipes/gujarati-dry-mung-bean-curry-1353775\"\u003EGujarati Dry Mung Bean Curry\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/gujarati-dry-mung-bean-curry-1520647\"\u003EGujarati Dry Mung Bean Curry\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/uncle-bills-mung-bean-curry-1283881\"\u003EUncle Bill's Mung Bean Curry\u003C/a\u003E are very similar to this recipe.",
    "cuisines": [
      "Indian",
      "Asian"
    ],
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 95.7149658203125,
    "spoonacularSourceUrl": "https://spoonacular.com/gujarati-dry-mung-bean-curry-646043"
  },
  {
    "id": 664680,
    "image": "https://img.spoonacular.com/recipes/664680-312x231.jpg",
    "imageType": "jpg",
    "title": "Vegetarian Mushroom Shepherd's Pie",
    "readyInMinutes": 45,
    "servings": 12,
    "sourceUrl": "https://www.foodista.com/recipe/Q8LZSX4D/vegetarian-mushroom-shepherd-s-pie-with-vegan-version",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 3,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 11,
    "healthScore": 66,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 116.49,
    "summary": "The recipe Vegetarian Mushroom Shepherd's Pie is ready \u003Cb\u003Ein around 45 minutes\u003C/b\u003E and is definitely an awesome \u003Cb\u003Egluten free and dairy free\u003C/b\u003E option for lovers of European food. For \u003Cb\u003E$1.16 per serving\u003C/b\u003E, you get a hor d'oeuvre that serves 12. One serving contains \u003Cb\u003E113 calories\u003C/b\u003E, \u003Cb\u003E5g of protein\u003C/b\u003E, and \u003Cb\u003E5g of fat\u003C/b\u003E. 11 person were glad they tried this recipe. This recipe from Foodista requires ground pepper, thyme, unrefined sunflower oil, and paprika. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 83%\u003C/b\u003E. This score is spectacular. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/vegetarian-mushroom-shepherds-pie-1404517\"\u003EVegetarian Mushroom Shepherd's Pie\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/vegetarian-mushroom-shepherds-pie-1374865\"\u003EVegetarian Mushroom Shepherd's Pie\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/vegetarian-mushroom-shepherds-pie-with-vegan-version-122196\"\u003EVegetarian Mushroom Shepherd's Pie - With Vegan Version\u003C/a\u003E.",
    "cuisines": [
      "English",
      "Scottish",
      "British",
      "European"
    ],
    "dishTypes": [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [],
    "spoonacularScore": 95.5406875610352,
    "spoonacularSourceUrl": "https://spoonacular.com/vegetarian-mushroom-shepherds-pie-664680"
  },
  {
    "id": 715391,
    "image": "https://img.spoonacular.com/recipes/715391-312x231.jpg",
    "imageType": "jpg",
    "title": "Slow Cooker Chicken Taco Soup",
    "readyInMinutes": 485,
    "servings": 6,
    "sourceUrl": "https://www.pinkwhen.com/slow-cooker-chicken-taco-soup-recipe/",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": true,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 7,
    "gaps": "no",
    "preparationMinutes": 5,
    "cookingMinutes": 480,
    "aggregateLikes": 2182,
    "healthScore": 28,
    "creditsText": "pinkwhen.com",
    "license": null,
    "sourceName": "pinkwhen.com",
    "pricePerServing": 141.43,
    "summary": "Forget going out to eat or ordering takeout every time you crave Mexican food. Try making Slow Cooker Chicken Taco Soup at home. One portion of this dish contains about \u003Cb\u003E24g of protein\u003C/b\u003E, \u003Cb\u003E4g of fat\u003C/b\u003E, and a total of \u003Cb\u003E312 calories\u003C/b\u003E. This gluten free and dairy free recipe serves 6 and costs \u003Cb\u003E$1.41 per serving\u003C/b\u003E. 2182 people have tried and liked this recipe. It works well as a main course. If you have black beans, chili beans, canned tomatoes, and a few other ingredients on hand, you can make it. It is perfect for \u003Cb\u003EAutumn\u003C/b\u003E. From preparation to the plate, this recipe takes around \u003Cb\u003E8 hours and 5 minutes\u003C/b\u003E. It is brought to you by Pink When. Overall, this recipe earns an \u003Cb\u003Eawesome spoonacular score of 95%\u003C/b\u003E. Users who liked this recipe also liked \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-chicken-taco-soup-1399115\"\u003ESlow Cooker Chicken Taco Soup\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-chicken-taco-soup-1228993\"\u003ESlow Cooker Chicken Taco Soup\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-chicken-taco-soup-1369307\"\u003ESlow Cooker Chicken Taco Soup\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "soup",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [
      "fall",
      "winter"
    ],
    "spoonacularScore": 95.5313110351563,
    "spoonacularSourceUrl": "https://spoonacular.com/slow-cooker-chicken-taco-soup-715391"
  },
  {
    "id": 716217,
    "image": "https://img.spoonacular.com/recipes/716217-312x231.jpg",
    "imageType": "jpg",
    "title": "Vietnamese Pancakes with Vegetables, Herbs and a Fragrant Dipping Sauce (Bánh Xèo)",
    "readyInMinutes": 45,
    "servings": 6,
    "sourceUrl": "https://www.foodandspice.com/2012/05/vietnamese-pancakes-with-vegetables.html",
    "vegetarian": true,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 14,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 295,
    "healthScore": 35,
    "creditsText": "foodandspice.com",
    "license": null,
    "sourceName": "foodandspice.com",
    "pricePerServing": 318.98,
    "summary": "Vietnamese Pancakes with Vegetables, Herbs and a Fragrant Dipping Sauce (Bánh Xèo) requires roughly \u003Cb\u003E45 minutes\u003C/b\u003E from start to finish. One serving contains \u003Cb\u003E390 calories\u003C/b\u003E, \u003Cb\u003E8g of protein\u003C/b\u003E, and \u003Cb\u003E22g of fat\u003C/b\u003E. This gluten free, dairy free, and lacto ovo vegetarian recipe serves 6 and costs \u003Cb\u003E$3.19 per serving\u003C/b\u003E. Head to the store and pick up chilies, rice vinegar, enoki mushrooms, and a few other things to make it today. 295 people found this recipe to be yummy and satisfying. It works well as a side dish. Plenty of people really liked this Vietnamese dish. It is brought to you by foodandspice.blogspot.com. Overall, this recipe earns an \u003Cb\u003Eawesome spoonacular score of 94%\u003C/b\u003E. Similar recipes include \u003Ca href=\"https://spoonacular.com/recipes/bnh-xo-vietnamese-happy-pancakes-891106\"\u003EBánh xèo (Vietnamese Happy Pancakes)\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/banh-xeo-bnh-xo-savory-vietnamese-crpe-1000958\"\u003EBanh Xeo (Bánh Xèo) – Savory Vietnamese Crêpe\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/banh-xeo-vietnamese-crepes-1661759\"\u003EBanh Xeo (Vietnamese Crepes)\u003C/a\u003E.",
    "cuisines": [
      "Vietnamese",
      "Asian"
    ],
    "dishTypes": [
      "side dish"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian"
    ],
    "occasions": [],
    "spoonacularScore": 95.2548217773438,
    "spoonacularSourceUrl": "https://spoonacular.com/vietnamese-pancakes-with-vegetables-herbs-and-a-fragrant-dipping-sauce-bnh-xo-716217"
  },
  {
    "id": 659109,
    "image": "https://img.spoonacular.com/recipes/659109-312x231.jpg",
    "imageType": "jpg",
    "title": "Salmon Quinoa Risotto",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/KH5STR7N/salmon-quinoa-risotto",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 10,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 3,
    "healthScore": 100,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 382.96,
    "summary": "Salmon Quinoa Risotto might be just the main course you are searching for. One serving contains \u003Cb\u003E437 calories\u003C/b\u003E, \u003Cb\u003E25g of protein\u003C/b\u003E, and \u003Cb\u003E20g of fat\u003C/b\u003E. This recipe serves 4. For \u003Cb\u003E$3.83 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 43%\u003C/b\u003E of your daily requirements of vitamins and minerals. Head to the store and pick up quinoa, poached salmon, olive oil, and a few other things to make it today. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, and pescatarian\u003C/b\u003E diet. It is a \u003Cb\u003Erather expensive\u003C/b\u003E recipe for fans of Mediterranean food. 3 people found this recipe to be yummy and satisfying. From preparation to the plate, this recipe takes roughly \u003Cb\u003E45 minutes\u003C/b\u003E. It is brought to you by Foodista. Overall, this recipe earns an \u003Cb\u003Eoutstanding spoonacular score of 94%\u003C/b\u003E. Similar recipes include \u003Ca href=\"https://spoonacular.com/recipes/salmon-quinoa-risotto-1360771\"\u003ESalmon Quinoa Risotto\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/salmon-quinoa-risotto-1288579\"\u003ESalmon Quinoa Risotto\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/quinoa-risotto-with-salmon-and-kale-15276\"\u003EQuinoa Risotto With Salmon And Kale\u003C/a\u003E.",
    "cuisines": [
      "Mediterranean",
      "Italian",
      "European"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "pescatarian"
    ],
    "occasions": [],
    "spoonacularScore": 95.1843414306641,
    "spoonacularSourceUrl": "https://spoonacular.com/salmon-quinoa-risotto-659109"
  },
  {
    "id": 644826,
    "image": "https://img.spoonacular.com/recipes/644826-312x231.jpg",
    "imageType": "jpg",
    "title": "Gluten Free Dairy Free Sugar Free Chinese Chicken Salad",
    "readyInMinutes": 45,
    "servings": 6,
    "sourceUrl": "https://www.foodista.com/recipe/ZSNGMXBF/gluten-free-dairy-free-sugar-free-chinese-chicken-salad",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 6,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 3,
    "healthScore": 98,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 305.98,
    "summary": "Gluten Free Dairy Free Sugar Free Chinese Chicken Salad is a \u003Cb\u003Egluten free and dairy free\u003C/b\u003E main course. This recipe serves 6 and costs $3.06 per serving. One serving contains \u003Cb\u003E364 calories\u003C/b\u003E, \u003Cb\u003E31g of protein\u003C/b\u003E, and \u003Cb\u003E15g of fat\u003C/b\u003E. If you have scallions, pepper, kosher salt, and a few other ingredients on hand, you can make it. This recipe from Foodista has 3 fans. Not a lot of people really liked this Chinese dish. From preparation to the plate, this recipe takes about \u003Cb\u003E45 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 94%\u003C/b\u003E, this dish is great. If you like this recipe, take a look at these similar recipes: \u003Ca href=\"https://spoonacular.com/recipes/gluten-free-dairy-free-sugar-free-chinese-chicken-salad-1364955\"\u003EGluten Free Dairy Free Sugar Free Chinese Chicken Salad\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/thousand-island-dressing-gluten-free-corn-free-dairy-free-soy-free-nut-free-gum-free-and-refined-sugar-free-512186\"\u003EThousand Island Dressing (Gluten-Free, Corn-Free, Dairy-Free, Soy-Free, Nut-Free, Gum-Free and Refined Sugar-Free)\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/skinny-double-chocolate-muffins-vegan-gluten-free-dairy-free-egg-free-and-refined-sugar-free-1149614\"\u003ESkinny Double Chocolate Muffins-Vegan, Gluten Free, Dairy Free, Egg Free and Refined Sugar Free\u003C/a\u003E.",
    "cuisines": [
      "Chinese",
      "Asian"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "salad",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [],
    "spoonacularScore": 95.176872253418,
    "spoonacularSourceUrl": "https://spoonacular.com/gluten-free-dairy-free-sugar-free-chinese-chicken-salad-644826"
  },
  {
    "id": 716364,
    "image": "https://img.spoonacular.com/recipes/716364-312x231.jpg",
    "imageType": "jpg",
    "title": "Rice and Peas with Coconut Curry Mackerel",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.afrolems.com/2014/10/31/rice-and-peas-with-coconut-curry-mackerel/",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 22,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 26,
    "healthScore": 52,
    "creditsText": "afrolems.com",
    "license": null,
    "sourceName": "afrolems.com",
    "pricePerServing": 243.53,
    "summary": "Rice and Peas with Coconut Curry Mackerel could be just the \u003Cb\u003Egluten free and dairy free\u003C/b\u003E recipe you've been looking for. For \u003Cb\u003E$2.44 per serving\u003C/b\u003E, you get a main course that serves 4. One serving contains \u003Cb\u003E625 calories\u003C/b\u003E, \u003Cb\u003E31g of protein\u003C/b\u003E, and \u003Cb\u003E34g of fat\u003C/b\u003E. This recipe from Afrolems has 26 fans. From preparation to the plate, this recipe takes around \u003Cb\u003E45 minutes\u003C/b\u003E. If you have coconut milk, corn starch, garlic, and a few other ingredients on hand, you can make it. A couple people really liked this Indian dish. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 94%\u003C/b\u003E. This score is super. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/rice-and-peas-with-coconut-curry-mackerel-1585999\"\u003ERice and Peas with Coconut Curry Mackerel\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/coconut-chicken-curry-with-snow-peas-and-rice-1213727\"\u003ECoconut Chicken Curry with Snow Peas and Rice\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/black-eyed-peas-curry-with-coconut-lobia-curry-600742\"\u003EBlack Eyed Peas Curry (With Coconut) (Lobia Curry)\u003C/a\u003E.",
    "cuisines": [
      "Indian",
      "Asian"
    ],
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [],
    "spoonacularScore": 94.8420562744141,
    "spoonacularSourceUrl": "https://spoonacular.com/rice-and-peas-with-coconut-curry-mackerel-716364"
  },
  {
    "id": 665379,
    "image": "https://img.spoonacular.com/recipes/665379-312x231.jpg",
    "imageType": "jpg",
    "title": "Winter Kimchi",
    "readyInMinutes": 45,
    "servings": 1,
    "sourceUrl": "https://www.foodista.com/recipe/DPZ3FLTW/winter-kimchi",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 6,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 4,
    "healthScore": 100,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 1050.81,
    "summary": "Need a \u003Cb\u003Egluten free, dairy free, and pescatarian side dish\u003C/b\u003E? Winter Kimchi could be a spectacular recipe to try. This recipe makes 1 servings with \u003Cb\u003E365 calories\u003C/b\u003E, \u003Cb\u003E23g of protein\u003C/b\u003E, and \u003Cb\u003E3g of fat\u003C/b\u003E each. For \u003Cb\u003E$10.51 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 54%\u003C/b\u003E of your daily requirements of vitamins and minerals. Not a lot of people really liked this Korean dish. It will be a hit at your \u003Cb\u003EWinter\u003C/b\u003E event. If you have fish sauce, brine solution, garlic bulb, and a few other ingredients on hand, you can make it. 4 people found this recipe to be delicious and satisfying. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 92%\u003C/b\u003E, this dish is amazing. \u003Ca href=\"https://spoonacular.com/recipes/winter-kimchi-1404513\"\u003EWinter Kimchi\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/kimchi-stew-with-pork-belly-and-tofu-kimchi-jjigae-1679959\"\u003EKimchi Stew with Pork Belly and Tofu (Kimchi-jjigae)\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/red-curry-mussels-with-kimchi-puree-from-the-kimchi-cookbook-202500\"\u003ERed Curry Mussels with Kimchi Puree from 'The Kimchi Cookbook\u003C/a\u003E are very similar to this recipe.",
    "cuisines": [
      "Korean",
      "Asian"
    ],
    "dishTypes": [
      "side dish"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "pescatarian"
    ],
    "occasions": [
      "winter"
    ],
    "spoonacularScore": 94.1884078979492,
    "spoonacularSourceUrl": "https://spoonacular.com/winter-kimchi-665379"
  },
  {
    "id": 660231,
    "image": "https://img.spoonacular.com/recipes/660231-312x231.jpg",
    "imageType": "jpg",
    "title": "Skinny Veggie Fried Rice",
    "readyInMinutes": 45,
    "servings": 2,
    "sourceUrl": "https://www.foodista.com/recipe/S53BXV6Z/skinny-veggie-fried-rice",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 4,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 8,
    "healthScore": 61,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 125.93,
    "summary": "If you have approximately \u003Cb\u003E45 minutes\u003C/b\u003E to spend in the kitchen, Skinny Veggie Fried Rice might be a spectacular \u003Cb\u003Egluten free, dairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E recipe to try. This recipe serves 2 and costs $1.26 per serving. One portion of this dish contains about \u003Cb\u003E5g of protein\u003C/b\u003E, \u003Cb\u003E9g of fat\u003C/b\u003E, and a total of \u003Cb\u003E157 calories\u003C/b\u003E. It works well as a Chinese hor d'oeuvre. This recipe is liked by 8 foodies and cooks. A mixture of sesame oil, bell pepper, garlic, and a handful of other ingredients are all it takes to make this recipe so flavorful. It is brought to you by Foodista. With a spoonacular \u003Cb\u003Escore of 92%\u003C/b\u003E, this dish is outstanding. Users who liked this recipe also liked \u003Ca href=\"https://spoonacular.com/recipes/skinny-veggie-fried-rice-1315153\"\u003ESkinny Veggie Fried Rice\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/skinny-veggie-fried-rice-1326473\"\u003ESkinny Veggie Fried Rice\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/skinny-chicken-fried-rice-1273519\"\u003ESkinny Chicken Fried Rice\u003C/a\u003E.",
    "cuisines": [
      "Chinese",
      "Asian"
    ],
    "dishTypes": [
      "side dish",
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 94.1435241699219,
    "spoonacularSourceUrl": "https://spoonacular.com/skinny-veggie-fried-rice-660231"
  },
  {
    "id": 647875,
    "image": "https://img.spoonacular.com/recipes/647875-312x231.jpg",
    "imageType": "jpg",
    "title": "Indian-Style Dill and Turmeric Potato Salad",
    "readyInMinutes": 30,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/2LQW8RTQ/indian-style-dill-and-turmeric-potatoes",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 12,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 4,
    "healthScore": 73,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 117.24,
    "summary": "Indian-Style Dill and Turmeric Potato Salad might be just the \u003Cb\u003EIndian\u003C/b\u003E recipe you are searching for. This gluten free, dairy free, lacto ovo vegetarian, and whole 30 recipe serves 4 and costs \u003Cb\u003E$1.17 per serving\u003C/b\u003E. One serving contains \u003Cb\u003E416 calories\u003C/b\u003E, \u003Cb\u003E8g of protein\u003C/b\u003E, and \u003Cb\u003E14g of fat\u003C/b\u003E. Not a lot of people made this recipe, and 4 would say it hit the spot. It works well as an affordable side dish. It can be enjoyed any time, but it is especially good for \u003Cb\u003EThe Fourth Of July\u003C/b\u003E. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately \u003Cb\u003E30 minutes\u003C/b\u003E. Head to the store and pick up olive oil, turmeric powder, potatoes, and a few other things to make it today. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 96%\u003C/b\u003E, which is awesome. Similar recipes include \u003Ca href=\"https://spoonacular.com/recipes/indian-style-dill-and-turmeric-potato-salad-1364367\"\u003EIndian-Style Dill and Turmeric Potato Salad\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/turmeric-potato-salad-906713\"\u003ETurmeric Potato Salad\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/potato-podimas-how-to-make-potato-podimas-south-indian-style-487619\"\u003Epotato podimas , how to make potato podimas | south indian style\u003C/a\u003E.",
    "cuisines": [
      "Indian",
      "Asian"
    ],
    "dishTypes": [
      "side dish"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "whole 30",
      "vegan"
    ],
    "occasions": [
      "father's day",
      "4th of july",
      "summer"
    ],
    "spoonacularScore": 94.096435546875,
    "spoonacularSourceUrl": "https://spoonacular.com/indian-style-dill-and-turmeric-potato-salad-647875"
  },
  {
    "id": 664419,
    "image": "https://img.spoonacular.com/recipes/664419-312x231.jpg",
    "imageType": "jpg",
    "title": "Vegan Colcannon Soup",
    "readyInMinutes": 45,
    "servings": 8,
    "sourceUrl": "https://www.foodista.com/recipe/LKGLSJ48/vegan-colcannon-soup",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 4,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 100,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 148.35,
    "summary": "Vegan Colcannon Soup is an European recipe that serves 8. Watching your figure? This gluten free, dairy free, lacto ovo vegetarian, and whole 30 recipe has \u003Cb\u003E203 calories\u003C/b\u003E, \u003Cb\u003E7g of protein\u003C/b\u003E, and \u003Cb\u003E5g of fat\u003C/b\u003E per serving. For \u003Cb\u003E$1.48 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 25%\u003C/b\u003E of your daily requirements of vitamins and minerals. \u003Cb\u003EAutumn\u003C/b\u003E will be even more special with this recipe. 1 person were impressed by this recipe. It works well as a rather cheap hor d'oeuvre. This recipe from Foodista requires pepper, juice of lemon, garlic, and russet potatoes. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. Overall, this recipe earns a \u003Cb\u003Egreat spoonacular score of 82%\u003C/b\u003E. Try \u003Ca href=\"https://spoonacular.com/recipes/vegan-colcannon-soup-1183083\"\u003EVegan Colcannon Soup\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/vegan-colcannon-92687\"\u003EVegan Colcannon\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/colcannon-bites-with-collard-greens-vegan-866599\"\u003EColcannon Bites With Collard Greens (Vegan)\u003C/a\u003E for similar recipes.",
    "cuisines": [
      "European",
      "Irish"
    ],
    "dishTypes": [
      "antipasti",
      "soup",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "whole 30",
      "vegan"
    ],
    "occasions": [
      "fall",
      "winter"
    ],
    "spoonacularScore": 94.0921936035156,
    "spoonacularSourceUrl": "https://spoonacular.com/vegan-colcannon-soup-664419"
  },
  {
    "id": 982382,
    "image": "https://img.spoonacular.com/recipes/982382-312x231.jpg",
    "imageType": "jpg",
    "title": "Instant Pot Chicken Taco Soup",
    "readyInMinutes": 25,
    "servings": 4,
    "sourceUrl": "https://www.pinkwhen.com/instant-pot-chicken-taco-soup/",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 6,
    "gaps": "no",
    "preparationMinutes": 5,
    "cookingMinutes": 20,
    "aggregateLikes": 3,
    "healthScore": 83,
    "creditsText": "pinkwhen.com",
    "license": null,
    "sourceName": "pinkwhen.com",
    "pricePerServing": 271.9,
    "summary": "Need a \u003Cb\u003Egluten free and dairy free main course\u003C/b\u003E? Instant Pot Chicken Taco Soup could be an excellent recipe to try. One portion of this dish contains approximately \u003Cb\u003E25g of protein\u003C/b\u003E, \u003Cb\u003E8g of fat\u003C/b\u003E, and a total of \u003Cb\u003E346 calories\u003C/b\u003E. This recipe serves 4 and costs $2.72 per serving. Head to the store and pick up chili powder, black beans, green onion, and a few other things to make it today. It is brought to you by Pink When. 3 people were impressed by this recipe. It will be a hit at your \u003Cb\u003EAutumn\u003C/b\u003E event. Only a few people really liked this Mexican dish. From preparation to the plate, this recipe takes approximately \u003Cb\u003E25 minutes\u003C/b\u003E. With a spoonacular \u003Cb\u003Escore of 92%\u003C/b\u003E, this dish is great. Users who liked this recipe also liked \u003Ca href=\"https://spoonacular.com/recipes/instant-pot-chicken-taco-soup-975070\"\u003EInstant Pot Chicken Taco Soup\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/instant-pot-chicken-taco-soup-1351299\"\u003EInstant Pot Chicken Taco Soup\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/instant-pot-chicken-taco-soup-1032489\"\u003EInstant Pot Chicken Taco Soup\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "soup",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free"
    ],
    "occasions": [
      "fall",
      "winter"
    ],
    "spoonacularScore": 93.8903350830078,
    "spoonacularSourceUrl": "https://spoonacular.com/instant-pot-chicken-taco-soup-982382"
  },
  {
    "id": 648279,
    "image": "https://img.spoonacular.com/recipes/648279-312x231.jpg",
    "imageType": "jpg",
    "title": "Italian Tuna Pasta",
    "readyInMinutes": 20,
    "servings": 3,
    "sourceUrl": "https://www.foodista.com/recipe/4QNQXMDZ/italian-tuna-pasta",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": false,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 10,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 100,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 209.48,
    "summary": "Italian Tuna Pastan is a Mediterranean main course. Watching your figure? This dairy free and pescatarian recipe has \u003Cb\u003E464 calories\u003C/b\u003E, \u003Cb\u003E38g of protein\u003C/b\u003E, and \u003Cb\u003E3g of fat\u003C/b\u003E per serving. For \u003Cb\u003E$2.09 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 35%\u003C/b\u003E of your daily requirements of vitamins and minerals. This recipe serves 3. 1 person found this recipe to be yummy and satisfying. From preparation to the plate, this recipe takes around \u003Cb\u003E20 minutes\u003C/b\u003E. It is brought to you by Foodista. A mixture of chillies, pasta shells, juice of lemon, and a handful of other ingredients are all it takes to make this recipe so tasty. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 93%\u003C/b\u003E, which is excellent. Try \u003Ca href=\"https://spoonacular.com/recipes/italian-tuna-pasta-salad-413394\"\u003EItalian Tuna Pasta Salad\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/pasta-and-tuna-salad-ensalada-de-pasta-y-atn-226303\"\u003EPastan and Tuna Salad (Ensalada de Pasta y Atún)\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/raw-tomato-sauce-for-pasta-the-italian-pasta-alla-crudaiola-1530081\"\u003ERaw tomato sauce for pasta, the Italian pastan alla crudaiola\u003C/a\u003E for similar recipes.",
    "cuisines": [
      "Mediterranean",
      "Italian",
      "European"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "dairy free",
      "pescatarian"
    ],
    "occasions": [],
    "spoonacularScore": 93.8249969482422,
    "spoonacularSourceUrl": "https://spoonacular.com/italian-tuna-pasta-648279"
  },
  {
    "id": 633754,
    "image": "https://img.spoonacular.com/recipes/633754-312x231.jpg",
    "imageType": "jpg",
    "title": "Baked Ratatouille",
    "readyInMinutes": 45,
    "servings": 1,
    "sourceUrl": "https://www.foodista.com/recipe/24CCF5WL/baked-ratatouille",
    "vegetarian": true,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": false,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 27,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 2,
    "healthScore": 100,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 861.26,
    "summary": "Baked Ratatouille takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E from beginning to end. This recipe makes 1 servings with \u003Cb\u003E1029 calories\u003C/b\u003E, \u003Cb\u003E32g of protein\u003C/b\u003E, and \u003Cb\u003E70g of fat\u003C/b\u003E each. For \u003Cb\u003E$8.61 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 63%\u003C/b\u003E of your daily requirements of vitamins and minerals. It works well as a main course. This recipe is typical of Mediterranean cuisine. If you have eggplant, bell peppers, olive oil, and a few other ingredients on hand, you can make it. It is a good option if you're following a \u003Cb\u003Egluten free, lacto ovo vegetarian, and primal\u003C/b\u003E diet. It is brought to you by Foodista. 2 people were glad they tried this recipe. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 92%\u003C/b\u003E. This score is tremendous. If you like this recipe, take a look at these similar recipes: \u003Ca href=\"https://spoonacular.com/recipes/baked-ratatouille-432644\"\u003EBaked Ratatouille\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/baked-ratatouille-106358\"\u003EBaked Ratatouille\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/baked-ratatouille-1379565\"\u003EBaked Ratatouille\u003C/a\u003E.",
    "cuisines": [
      "Mediterranean",
      "French",
      "European"
    ],
    "dishTypes": [
      "side dish",
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "lacto ovo vegetarian",
      "primal"
    ],
    "occasions": [],
    "spoonacularScore": 93.8123931884766,
    "spoonacularSourceUrl": "https://spoonacular.com/baked-ratatouille-633754"
  },
  {
    "id": 637157,
    "image": "https://img.spoonacular.com/recipes/637157-312x231.jpg",
    "imageType": "jpg",
    "title": "Carolina Caviar - Black Bean Salsa",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/YX8KH6ZY/carolina-caviar-black-bean-salsa",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 11,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 100,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 228.65,
    "summary": "Carolina Caviar - Black Bean Salsa requires about \u003Cb\u003E45 minutes\u003C/b\u003E from start to finish. This hor d'oeuvre has \u003Cb\u003E433 calories\u003C/b\u003E, \u003Cb\u003E15g of protein\u003C/b\u003E, and \u003Cb\u003E17g of fat\u003C/b\u003E per serving. This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe serves 4 and costs \u003Cb\u003E$2.29 per serving\u003C/b\u003E. 1 person were glad they tried this recipe. Only a few people really liked this Mexican dish. Head to the store and pick up orange bell pepper, avocados, juice of lime, and a few other things to make it today. It is brought to you by Foodista. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 90%\u003C/b\u003E, which is super. Users who liked this recipe also liked \u003Ca href=\"https://spoonacular.com/recipes/black-bean-salsa-oklahoma-caviar-550058\"\u003EBlack Bean Salsa -Oklahoma Caviar\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/plantains-with-caviar-and-black-bean-puree-255894\"\u003EPlantains with Caviar and Black Bean Puree\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/black-bean-black-eyed-pea-salsa-100694\"\u003EBlack Bean & Black-Eyed Pea Salsa\u003C/a\u003E.",
    "cuisines": [
      "Mexican"
    ],
    "dishTypes": [
      "antipasti",
      "condiment",
      "starter",
      "snack",
      "appetizer",
      "dip",
      "antipasto",
      "hor d'oeuvre",
      "spread"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 93.7604141235352,
    "spoonacularSourceUrl": "https://spoonacular.com/carolina-caviar-black-bean-salsa-637157"
  },
  {
    "id": 660290,
    "image": "https://img.spoonacular.com/recipes/660290-312x231.jpg",
    "imageType": "jpg",
    "title": "Slow Cooker Lamb Curry",
    "readyInMinutes": 45,
    "servings": 8,
    "sourceUrl": "https://www.foodista.com/recipe/Z5MXNR2V/slow-cooker-lamb-curry",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": false,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 12,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 19,
    "healthScore": 49,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 360.46,
    "summary": "The recipe Slow Cooker Lamb Curry could satisfy your Indian craving in about \u003Cb\u003E45 minutes\u003C/b\u003E. This recipe serves 8. For \u003Cb\u003E$3.6 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 40%\u003C/b\u003E of your daily requirements of vitamins and minerals. One serving contains \u003Cb\u003E567 calories\u003C/b\u003E, \u003Cb\u003E67g of protein\u003C/b\u003E, and \u003Cb\u003E24g of fat\u003C/b\u003E. 19 people were impressed by this recipe. Head to the store and pick up fennel powder, oregano, garam masala, and a few other things to make it today. It is a good option if you're following a \u003Cb\u003Egluten free\u003C/b\u003E diet. It works well as a pretty expensive main course. It is brought to you by Foodista. With a spoonacular \u003Cb\u003Escore of 92%\u003C/b\u003E, this dish is super. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-lamb-curry-1583131\"\u003ESlow cooker lamb curry\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-lamb-stew-1146747\"\u003ESlow Cooker Lamb Stew\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/slow-cooker-lamb-shanks-484177\"\u003ESlow Cooker Lamb Shanks\u003C/a\u003E.",
    "cuisines": [
      "Indian",
      "Asian"
    ],
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free"
    ],
    "occasions": [],
    "spoonacularScore": 93.4943389892578,
    "spoonacularSourceUrl": "https://spoonacular.com/slow-cooker-lamb-curry-660290"
  },
  {
    "id": 637440,
    "image": "https://img.spoonacular.com/recipes/637440-312x231.jpg",
    "imageType": "jpg",
    "title": "Chapchae (Korean Stir-Fried Noodles)",
    "readyInMinutes": 45,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/RSDBG48H/chapchae-korean-stir-fried-noodles",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": false,
    "dairyFree": true,
    "veryHealthy": false,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 12,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 40,
    "healthScore": 38,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 208.61,
    "summary": "Chapchae (Korean Stir-Fried Noodles) is a \u003Cb\u003Edairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E recipe with 4 servings. This side dish has \u003Cb\u003E397 calories\u003C/b\u003E, \u003Cb\u003E5g of protein\u003C/b\u003E, and \u003Cb\u003E15g of fat\u003C/b\u003E per serving. For \u003Cb\u003E$2.09 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 21%\u003C/b\u003E of your daily requirements of vitamins and minerals. 40 people have made this recipe and would make it again. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. A few people really liked this Korean dish. A mixture of soy sauce, salt, baby spinach, and a handful of other ingredients are all it takes to make this recipe so scrumptious. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 91%\u003C/b\u003E. This score is spectacular. Similar recipes include \u003Ca href=\"https://spoonacular.com/recipes/chapchae-korean-stir-fried-noodles-1569447\"\u003EChapchae (Korean Stir-Fried Noodles)\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/chapchae-korean-stir-fried-noodles-1250231\"\u003EChapchae (Korean Stir-Fried Noodles)\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/korean-stir-fried-noodles-chapchae-604806\"\u003EKorean Stir-Fried Noodles (Chapchae)\u003C/a\u003E.",
    "cuisines": [
      "Korean",
      "Asian"
    ],
    "dishTypes": [
      "side dish"
    ],
    "diets": [
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 93.2965240478516,
    "spoonacularSourceUrl": "https://spoonacular.com/chapchae-korean-stir-fried-noodles-637440"
  },
  {
    "id": 663177,
    "image": "https://img.spoonacular.com/recipes/663177-312x231.jpg",
    "imageType": "jpg",
    "title": "Thai-Style Mussels",
    "readyInMinutes": 45,
    "servings": 3,
    "sourceUrl": "https://www.foodista.com/recipe/VMQG43VB/thai-style-mussels",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 4,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 90,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 153.6,
    "summary": "If you want to add more \u003Cb\u003Egluten free, dairy free, paleolithic, and primal\u003C/b\u003E recipes to your recipe box, Thai-Style Mussels might be a recipe you should try. This recipe serves 3. One serving contains \u003Cb\u003E208 calories\u003C/b\u003E, \u003Cb\u003E21g of protein\u003C/b\u003E, and \u003Cb\u003E9g of fat\u003C/b\u003E. For \u003Cb\u003E$1.54 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 25%\u003C/b\u003E of your daily requirements of vitamins and minerals. 1 person were glad they tried this recipe. If you have chilies, water, olive oil, and a few other ingredients on hand, you can make it. Only a few people really liked this hor d'oeuvre. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. This recipe is typical of Asian cuisine. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 92%\u003C/b\u003E. This score is spectacular. Similar recipes are \u003Ca href=\"https://spoonacular.com/recipes/thai-style-mussels-with-lemongrass-493369\"\u003EThai-Style Mussels with Lemongrass\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/thai-style-steamed-mussels-with-coconut-milk-basil-76575\"\u003EThai-style Steamed Mussels With Coconut Milk & Basil\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/mussels-with-thai-seasonings-696546\"\u003EMussels with Thai Seasonings\u003C/a\u003E.",
    "cuisines": [
      "Thai",
      "Asian"
    ],
    "dishTypes": [
      "antipasti",
      "lunch",
      "main course",
      "starter",
      "snack",
      "appetizer",
      "main dish",
      "antipasto",
      "hor d'oeuvre",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "paleolithic",
      "primal",
      "pescatarian"
    ],
    "occasions": [],
    "spoonacularScore": 93.1554870605469,
    "spoonacularSourceUrl": "https://spoonacular.com/thai-style-mussels-663177"
  },
  {
    "id": 652078,
    "image": "https://img.spoonacular.com/recipes/652078-312x231.jpg",
    "imageType": "jpg",
    "title": "Miso Soup With Thin Noodles",
    "readyInMinutes": 45,
    "servings": 8,
    "sourceUrl": "https://www.foodista.com/recipe/BYJ4Q2M5/miso-soup-with-thin-noodles",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": false,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 2,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 86,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 100.84,
    "summary": "Miso Soup With Thin Noodles could be just the \u003Cb\u003Edairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E recipe you've been looking for. One portion of this dish contains around \u003Cb\u003E5g of protein\u003C/b\u003E, \u003Cb\u003E2g of fat\u003C/b\u003E, and a total of \u003Cb\u003E114 calories\u003C/b\u003E. For \u003Cb\u003E$1.01 per serving\u003C/b\u003E, you get a hor d'oeuvre that serves 8. It can be enjoyed any time, but it is especially good for \u003Cb\u003EAutumn\u003C/b\u003E. It is brought to you by Foodista. It is a \u003Cb\u003Ereasonably priced\u003C/b\u003E recipe for fans of Japanese food. 1 person found this recipe to be flavorful and satisfying. A mixture of thai kitchen rice noodles, spinach, baby carrots, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes approximately \u003Cb\u003E45 minutes\u003C/b\u003E. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 89%\u003C/b\u003E. This score is excellent. Try \u003Ca href=\"https://spoonacular.com/recipes/a-quick-and-easy-soup-miso-soup-with-soba-noodles-or-mung-bean-31003\"\u003EA Quick And Easy Soup {miso Soup With Soba Noodles Or Mung Bean\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/soba-noodles-with-miso-broth-37466\"\u003ESoba Noodles with Miso Broth\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/ginger-miso-noodles-with-eggplant-446340\"\u003Eginger miso noodles with eggplant\u003C/a\u003E for similar recipes.",
    "cuisines": [
      "Japanese",
      "Asian"
    ],
    "dishTypes": [
      "antipasti",
      "soup",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [
      "fall",
      "winter"
    ],
    "spoonacularScore": 93.1336975097656,
    "spoonacularSourceUrl": "https://spoonacular.com/miso-soup-with-thin-noodles-652078"
  },
  {
    "id": 1095745,
    "image": "https://img.spoonacular.com/recipes/1095745-312x231.jpg",
    "imageType": "jpg",
    "title": "Mushroom Hummus Crostini",
    "readyInMinutes": 30,
    "servings": 4,
    "sourceUrl": "https://www.foodista.com/recipe/DMRJSD86/mushroom-crostini-with-harissa-hummus",
    "vegetarian": true,
    "vegan": true,
    "glutenFree": false,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 12,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 92,
    "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    "license": "CC BY 3.0",
    "sourceName": "Foodista",
    "pricePerServing": 240.78,
    "summary": "Mushroom Hummus Crostini is a Mediterranean hor d'oeuvre. One serving contains \u003Cb\u003E450 calories\u003C/b\u003E, \u003Cb\u003E21g of protein\u003C/b\u003E, and \u003Cb\u003E10g of fat\u003C/b\u003E. This recipe serves 4 and costs $2.41 per serving. Head to the store and pick up water, mushrooms, harissa, and a few other things to make it today. 1 person were impressed by this recipe. From preparation to the plate, this recipe takes around \u003Cb\u003E30 minutes\u003C/b\u003E. It is a good option if you're following a \u003Cb\u003Edairy free, lacto ovo vegetarian, and vegan\u003C/b\u003E diet. It is brought to you by Foodista. Taking all factors into account, this recipe \u003Cb\u003Eearns a spoonacular score of 91%\u003C/b\u003E, which is super. If you like this recipe, take a look at these similar recipes: \u003Ca href=\"https://spoonacular.com/recipes/hummus-and-cucumber-crostini-22985\"\u003EHummus And Cucumber Crostini\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/seared-tuna-with-hummus-on-crostini-386082\"\u003ESeared Tuna with Hummus on Crostini\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/beet-hummus-and-caramelized-onion-crostini-703941\"\u003EBeet Hummus and Caramelized Onion Crostini\u003C/a\u003E.",
    "cuisines": [
      "Mediterranean",
      "Italian",
      "European"
    ],
    "dishTypes": [
      "fingerfood",
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre"
    ],
    "diets": [
      "dairy free",
      "lacto ovo vegetarian",
      "vegan"
    ],
    "occasions": [],
    "spoonacularScore": 92.9460220336914,
    "spoonacularSourceUrl": "https://spoonacular.com/mushroom-hummus-crostini-1095745"
  },
  {
    "id": 1095806,
    "image": "https://img.spoonacular.com/recipes/1095806-312x231.jpg",
    "imageType": "jpg",
    "title": "Spanish style salmon fillets",
    "readyInMinutes": 30,
    "servings": 2,
    "sourceUrl": "https://www.foodista.com/recipe/JS5W8D53/spanish-style-salmon-fillets",
    "vegetarian": false,
    "vegan": false,
    "glutenFree": true,
    "dairyFree": true,
    "veryHealthy": true,
    "cheap": false,
    "veryPopular": false,
    "sustainable": false,
    "lowFodmap": false,
    "weightWatcherSmartPoints": 25,
    "gaps": "no",
    "preparationMinutes": null,
    "cookingMinutes": null,
    "aggregateLikes": 1,
    "healthScore": 100,
    "creditsText": "foodista.com",
    "license": null,
    "sourceName": "foodista.com",
    "pricePerServing": 779.65,
    "summary": "If you want to add more \u003Cb\u003EEuropean\u003C/b\u003E recipes to your recipe box, Spanish style salmon fillets might be a recipe you should try. This recipe serves 2. One serving contains \u003Cb\u003E945 calories\u003C/b\u003E, \u003Cb\u003E53g of protein\u003C/b\u003E, and \u003Cb\u003E60g of fat\u003C/b\u003E. For \u003Cb\u003E$7.8 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 54%\u003C/b\u003E of your daily requirements of vitamins and minerals. 1 person were impressed by this recipe. This recipe from Foodista requires ground pepper, olives, salmon fillets, and coarse sea salt. It works well as an expensive main course. From preparation to the plate, this recipe takes around \u003Cb\u003E30 minutes\u003C/b\u003E. It is a good option if you're following a \u003Cb\u003Egluten free, dairy free, whole 30, and pescatarian\u003C/b\u003E diet. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 92%\u003C/b\u003E. This score is amazing. If you like this recipe, you might also like recipes such as \u003Ca href=\"https://spoonacular.com/recipes/tasty-salmon-fillets-asian-style-87364\"\u003ETasty Salmon Fillets Asian Style\u003C/a\u003E, \u003Ca href=\"https://spoonacular.com/recipes/crock-pot-salmon-fillets-and-asian-style-vegetables-1219451\"\u003ECrock Pot Salmon Fillets and Asian Style Vegetables\u003C/a\u003E, and \u003Ca href=\"https://spoonacular.com/recipes/crock-pot-salmon-fillets-and-asian-style-vegetables-524925\"\u003ECrock Pot Salmon Fillets and Asian Style Vegetables\u003C/a\u003E.",
    "cuisines": [
      "Spanish",
      "European"
    ],
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "diets": [
      "gluten free",
      "dairy free",
      "whole 30",
      "pescatarian"
    ],
    "occasions": [],
    "spoonacularScore": 92.8101272583008,
    "spoonacularSourceUrl": "https://spoonacular.com/spanish-style-salmon-fillets-1095806"
  }
]